// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/control-room-mission/MissionControl.tsx": () => import("../components/mockups/control-room-mission/MissionControl.tsx"),
  "./components/mockups/control-room-modular/ModularDeck.tsx": () => import("../components/mockups/control-room-modular/ModularDeck.tsx"),
  "./components/mockups/control-room-terminal/TerminalWall.tsx": () => import("../components/mockups/control-room-terminal/TerminalWall.tsx")
};
